package dev.springforge.cli;

import dev.springforge.generator.ConfigManager;
import dev.springforge.model.ForgeConfig;
import dev.springforge.model.ServiceDefinition;
import dev.springforge.util.ConsoleOutput;
import dev.springforge.util.FileUtils;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.*;

@Command(
    name = "setup-db",
    description = "Set up PostgreSQL database (Docker or local)"
)
public class SetupDbCommand implements Runnable {

    @Option(names = {"--docker", "-d"}, description = "Use Docker for PostgreSQL", defaultValue = "true")
    private boolean useDocker;

    @Option(names = {"--port", "-p"}, description = "PostgreSQL port", defaultValue = "5432")
    private int port;

    private final ConfigManager configManager = new ConfigManager();

    @Override
    public void run() {
        try {
            Path projectDir = Paths.get(System.getProperty("user.dir"));
            ForgeConfig config = configManager.loadOrFail(projectDir);

            ConsoleOutput.header("Setting Up Database");

            // Generate init script for creating the monolithic database
            StringBuilder initSql = new StringBuilder();
            initSql.append("-- Auto-generated by SpringForge\n");
            initSql.append("-- Creates the main monolithic database\n\n");

            String mainDbName = config.getProjectName().replace("-", "_") + "_db";
            initSql.append(String.format("CREATE DATABASE %s;%n", mainDbName));

            FileUtils.writeFile(projectDir.resolve("scripts/init-databases.sql"), initSql.toString());
            ConsoleOutput.created("scripts/init-databases.sql");

            // Update config
            config.getDatabase().setDockerManaged(useDocker);
            config.getDatabase().setPort(port);
            configManager.save(projectDir, config);

            ConsoleOutput.done("Database setup complete!");
            ConsoleOutput.newline();
            ConsoleOutput.info("Start PostgreSQL:");
            ConsoleOutput.command("docker-compose up -d");
            ConsoleOutput.newline();
            ConsoleOutput.info("Databases created:");
            ConsoleOutput.info("  • " + mainDbName);
            ConsoleOutput.newline();

        } catch (Exception e) {
            ConsoleOutput.error("Failed to setup database: " + e.getMessage());
            e.printStackTrace();
        }
    }
}
